
### Implementación de Algoritmo de Deutsch y Deutsch-Jozsa

1. Implemente las 4 funciones posibles de {0,1} a {0,1} usando el computador cuántico de IBM.

Dibujo de función

1.f(0) = 0 y f(1)=0

2.f(0) = 1 y f(1)=1

3.f(0) = 0 y f(1)=1

4.f(0) = 1 y f(1)=0

Matriz correpondiente


In [226]:
import numpy as np
print("1.")
matriz1 = np.array([[1, 1],
                   [0, 0]])
print(matriz1)
print("2.")
matriz1 = np.array([[0, 0],
                   [1, 1]])
print(matriz1)
print("3.")
matriz1 = np.array([[1, 0],
                   [0, 1]])
print(matriz1)
print("4.")
matriz1 = np.array([[0, 1],
                   [1, 0]])
print(matriz1)

1.
[[1 1]
 [0 0]]
2.
[[0 0]
 [1 1]]
3.
[[1 0]
 [0 1]]
4.
[[0 1]
 [1 0]]


Circuito Correspondiente


In [232]:
import numpy as np
from qiskit import QuantumCircuit, transpile
from qiskit_aer import Aer
from qiskit.visualization import plot_histogram
import matplotlib.pyplot as plt
from qiskit.circuit.library import UnitaryGate

# Función 3: Identidad (I)
def identity_function():
    simulator = Aer.get_backend('qasm_simulator')
    circuit = QuantumCircuit(1, 1)  # 1 qubit y 1 bit clásico
    circuit.measure(0, 0)
    return circuit

# Función 4: Negación (X)
def negation_function():
    simulator = Aer.get_backend('qasm_simulator')
    circuit = QuantumCircuit(1, 1)
    circuit.x(0)  # Aplica una compuerta X (NOT)
    circuit.measure(0, 0)
    return circuit

# Función 1: Función constante 0 (C0)
def constant_zero_function():
    simulator = Aer.get_backend('qasm_simulator')
    circuit = QuantumCircuit(1, 1)
    # No se aplica ninguna compuerta, siempre es 0
    circuit.measure(0, 0)
    return circuit

# Función 2: Función constante 1 (C1)
def constant_one_function():
    simulator = Aer.get_backend('qasm_simulator')
    circuit = QuantumCircuit(1, 1)
    circuit.x(0)  # Aplica una compuerta X para forzar un 1
    circuit.measure(0, 0)
    return circuit

# Simulador cuántico
simulator = Aer.get_backend('qasm_simulator')


# Ejecutar cada circuito
def execute_function(circuit):
    simulator = Aer.get_backend('qasm_simulator')  # Asegurarse de usar AerSimulator
    compiled_circuit = transpile(circuit,simulator)
    job = simulator.run(compiled_circuit, shots=1000)
    result = job.result()
    counts = result.get_counts()
    return counts

# Ejecución de cada una de las funciones
functions = [identity_function, negation_function, constant_zero_function, constant_one_function]
for func in functions:
    circuit = func()
    counts = execute_function(circuit)
    print(f"Resultados para la función {func.__name__}: {counts}")
    print(circuit)


Resultados para la función identity_function: {'0': 1000}
     ┌─┐
  q: ┤M├
     └╥┘
c: 1/═╩═
      0 
Resultados para la función negation_function: {'1': 1000}
     ┌───┐┌─┐
  q: ┤ X ├┤M├
     └───┘└╥┘
c: 1/══════╩═
           0 
Resultados para la función constant_zero_function: {'0': 1000}
     ┌─┐
  q: ┤M├
     └╥┘
c: 1/═╩═
      0 
Resultados para la función constant_one_function: {'1': 1000}
     ┌───┐┌─┐
  q: ┤ X ├┤M├
     └───┘└╥┘
c: 1/══════╩═
           0 


2.Verifique que el algoritmos de Deutsch funciona para comprobar cuáles de estas funciones son balanceadas o constantes.





In [5]:
import numpy as np
from qiskit import QuantumCircuit, transpile
from qiskit_aer import Aer
from qiskit.visualization import plot_histogram
import matplotlib.pyplot as plt
from qiskit.circuit.library import UnitaryGate

# Función para construir el circuito de Deutsch para una función Uf
def deutsch_circuit(function):
    circuit = QuantumCircuit(2, 1)  # Dos qubits: uno de entrada, uno auxiliar
    circuit.x(1)
    circuit.h(0)
    circuit.h(1)
    circuit.append(function, [0, 1])
    circuit.h(0)
    circuit.measure(0, 0)
    return circuit


# Crear los oráculos para las funciones
def function_constant_0():
    return QuantumCircuit(2).to_gate(label="Uf_0")

def function_constant_1():
    circuit = QuantumCircuit(2)
    circuit.x(1)
    return circuit.to_gate(label="Uf_1")

def function_balanced_identity():
    circuit = QuantumCircuit(2)
    circuit.cx(0, 1)
    return circuit.to_gate(label="Uf_x")

def function_balanced_negation():
    circuit = QuantumCircuit(2)
    circuit.cx(0, 1)
    circuit.x(1)
    return circuit.to_gate(label="Uf_x̄")

# Crear y ejecutar los circuitos para cada función
def execute_function(function):
    circuit = deutsch_circuit(function)
    simulator = Aer.get_backend('qasm_simulator')
    compiled_circuit = transpile(circuit, simulator)
    result = simulator.run(compiled_circuit, shots=1000).result()
    counts = result.get_counts()
    return counts

# Crear y ejecutar los circuitos para cada función
def execute_function_circuit(function):
    circuit = deutsch_circuit(function)
    simulator = Aer.get_backend('qasm_simulator')
    compiled_circuit = transpile(circuit, simulator)
    result = simulator.run(compiled_circuit, shots=1000).result()
    counts = result.get_counts()
    return circuit


# Ejecutar para cada función
oracles = [
    function_constant_0(),
    function_constant_1(),
    function_balanced_identity(),
    function_balanced_negation()
]

labels = ["Constante funcion 1", "Constante funcion 2", "Balanced funcion 3", "Balanced funcion 4"]
results = {}

for function, label in zip(oracles, labels):
    counts = execute_function(function)
    results[label] = counts
    print(f"Result for {label}: {counts}")
    circuit = execute_function_circuit(function)
    print(circuit)
    

Result for Constante funcion 1: {'0': 1000}
     ┌───┐     ┌───────┐┌───┐┌─┐
q_0: ┤ H ├─────┤0      ├┤ H ├┤M├
     ├───┤┌───┐│  Uf_0 │└───┘└╥┘
q_1: ┤ X ├┤ H ├┤1      ├──────╫─
     └───┘└───┘└───────┘      ║ 
c: 1/═════════════════════════╩═
                              0 
Result for Constante funcion 2: {'0': 1000}
     ┌───┐     ┌───────┐┌───┐┌─┐
q_0: ┤ H ├─────┤0      ├┤ H ├┤M├
     ├───┤┌───┐│  Uf_1 │└───┘└╥┘
q_1: ┤ X ├┤ H ├┤1      ├──────╫─
     └───┘└───┘└───────┘      ║ 
c: 1/═════════════════════════╩═
                              0 
Result for Balanced funcion 3: {'1': 1000}
     ┌───┐     ┌───────┐┌───┐┌─┐
q_0: ┤ H ├─────┤0      ├┤ H ├┤M├
     ├───┤┌───┐│  Uf_x │└───┘└╥┘
q_1: ┤ X ├┤ H ├┤1      ├──────╫─
     └───┘└───┘└───────┘      ║ 
c: 1/═════════════════════════╩═
                              0 
Result for Balanced funcion 4: {'1': 1000}
     ┌───┐     ┌────────┐┌───┐┌─┐
q_0: ┤ H ├─────┤0       ├┤ H ├┤M├
     ├───┤┌───┐│  Uf_x̄ │└───┘└╥┘
q_1: ┤ X ├┤ H ├┤1       ├──────

3. Implemente al menos 4 funciones con n= 4 (3 balanceadas y una constante) para probar el funcionamiento del algoritmo Deustch-Jozsa

In [ ]:
import numpy as np
from qiskit import QuantumCircuit, transpile
from qiskit_aer import Aer
from qiskit.visualization import plot_histogram
import matplotlib.pyplot as plt
from qiskit.circuit.library import UnitaryGate
from qiskit.visualization import  array_to_latex


# Función para construir el circuito Deutsch-Jozsa
def deutsch_jozsa_circuit(oracle, n):
    circuit = QuantumCircuit(n + 1, n) 
    circuit.h(range(n))  
    circuit.x(n)  
    circuit.h(n)  
    circuit.append(oracle, range(n + 1))  
    circuit.h(range(n))  
    circuit.measure(range(n), range(n)) 
    return circuit